services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn django_website.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=django_website.settings
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=BioBinDB
      - DATABASE_USER=user
      - DATABASE_PASSWORD=mysqlpass
    networks:
      - network1

  db:
    image: mysql:8.0.41
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=BioBinDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysqlpass
      - MYSQL_ROOT_PASSWORD=mysqlrootpass
    ports:
      - "3306:3306"
    networks:
      - network1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    depends_on:
      - app
    networks:
      - network1
  
  processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    volumes:
      - ./processor:/app  # Mount scraping scripts for development
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=BioBinDB
      - DATABASE_USER=user
      - DATABASE_PASSWORD=mysqlpass
    networks:
      - network1

networks:
  network1:
volumes:
  mysql_data: